const competition = {
  _id: { $oid: "6252ebe1d595c7d6a7a76ded" },
  code: "testBracket1",
  name: "World Cup 2022",
  submissionDeadline: { $date: "2022-11-20T15:00:00.000Z" },
  maxSubmissions: 2,
  competitionStart: { $date: "2022-11-20T16:00:00.000Z" },
  competitionEnd: { $date: "2022-12-18T18:00:00.000Z" },
  scoring: {
    group: {
      perTeam: 1,
      bonus: 1,
    },
    playoff: [
      {
        roundName: "Round of 16",
        roundNumber: 1,
        points: 2,
      },
      {
        roundName: "Quarter Final",
        roundNumber: 2,
        points: 4,
      },
      {
        roundName: "Semi Final",
        roundNumber: 3,
        points: 8,
      },
      {
        roundName: "Final",
        roundNumber: 4,
        points: 16,
      },
    ],
    champion: 32,
  },
  miscPicks: [
    {
      name: "thirdPlace",
      label: "Third Place",
      description: "Winner of the third place playoff",
      points: 16,
      info: {
        homeTeamGoals: 0,
        homeTeamPKs: 0,
        awayTeamGoals: 0,
        awayTeamPKs: 0,
        matchAccepted: false,
        homeTeamName: "Loser Match 7",
        awayTeamName: "Loser Match 8",
        matchNumber: 9,
        round: 1001,
        sport: "Soccer",
        type: "Playoff",
        getTeamsFrom: {
          home: {
            matchNumber: 7,
          },
          away: {
            matchNumber: 8,
          },
        },
      },
    },
    {
      name: "discipline",
      label: "Worst Discipline",
      description:
        "Team with the worst disciplinary record at the end of the tournament (most yellow and red cards).",
      points: 10,
    },
    {
      name: "topScorer",
      label: "Top Goalscorer",
      description:
        "Team with the player who wins the golden boot for most goals in the tournament",
      points: 10,
    },
  ],
  prize: {
    text: "One free year of ultimatescoreboard.com Ultimate level subscription.",
    link: "https://ultimatescoreboard.com",
  },
};

const matches = [
  {
    homeTeamGoals: null,
    awayTeamGoals: null,
    matchAccepted: false,
    homeTeamName: "Team A",
    awayTeamName: "Team B",
    matchNumber: 1,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "Group A",
    bracketCode: "testBracket1",
  },
  {
    homeTeamGoals: null,
    awayTeamGoals: null,
    matchAccepted: false,
    homeTeamName: "Team A",
    awayTeamName: "Team C",
    matchNumber: 2,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "Group A",
    bracketCode: "testBracket1",
  },
  {
    homeTeamGoals: null,
    awayTeamGoals: null,
    matchAccepted: false,
    homeTeamName: "Team B",
    awayTeamName: "Team C",
    matchNumber: 3,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "Group A",
    bracketCode: "testBracket1",
  },
  {
    homeTeamGoals: null,
    awayTeamGoals: null,
    matchAccepted: false,
    homeTeamName: "Team D",
    awayTeamName: "Team E",
    matchNumber: 4,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "Group B",
    bracketCode: "testBracket1",
  },
  {
    homeTeamGoals: null,
    awayTeamGoals: null,
    matchAccepted: false,
    homeTeamName: "Team D",
    awayTeamName: "Team F",
    matchNumber: 5,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "Group B",
    bracketCode: "testBracket1",
  },
  {
    homeTeamGoals: null,
    awayTeamGoals: null,
    matchAccepted: false,
    homeTeamName: "Team E",
    awayTeamName: "Team F",
    matchNumber: 6,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "Group B",
    bracketCode: "testBracket1",
  },
  {
    homeTeamGoals: 0,
    homeTeamPKs: 0,
    awayTeamGoals: 0,
    awayTeamPKs: 0,
    matchAccepted: false,
    homeTeamName: "Winner Group A",
    awayTeamName: "Runner Up Group B",
    matchNumber: 7,
    round: 1,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        groupName: "Group A",
        position: 1,
      },
      away: {
        groupName: "Group B",
        position: 2,
      },
    },
    bracketCode: "testBracket1",
  },
  {
    homeTeamGoals: 0,
    homeTeamPKs: 0,
    awayTeamGoals: 0,
    awayTeamPKs: 0,
    matchAccepted: false,
    homeTeamName: "Winner Group B",
    awayTeamName: "Runner Up Group A",
    matchNumber: 8,
    round: 1,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        groupName: "Group B",
        position: 1,
      },
      away: {
        groupName: "Group A",
        position: 2,
      },
    },
    bracketCode: "testBracket1",
  },
  {
    homeTeamGoals: 0,
    homeTeamPKs: 0,
    awayTeamGoals: 0,
    awayTeamPKs: 0,
    matchAccepted: false,
    homeTeamName: "Winner 7",
    awayTeamName: "Winner 8",
    matchNumber: 10,
    round: 2,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        matchNumber: 7,
      },
      away: {
        matchNumber: 8,
      },
    },
    bracketCode: "testBracket1",
  },
];

const unevenMatchesCompetition = {
  _id: { $oid: "684476236ba7e98fd4d5f7ad" },
  code: "testUnevenBracket1",
  name: "EURO 2024",
  submissionDeadline: { $date: "2022-11-20T15:00:00.000Z" },
  maxSubmissions: 2,
  competitionStart: { $date: "2022-11-20T16:00:00.000Z" },
  competitionEnd: { $date: "2022-12-18T18:00:00.000Z" },
  scoring: {
    group: {
      perTeam: 1,
      bonus: 1,
    },
    playoff: [
      {
        roundName: "Round of 16",
        roundNumber: 1,
        points: 2,
      },
      {
        roundName: "Quarter Final",
        roundNumber: 2,
        points: 4,
      },
      {
        roundName: "Semi Final",
        roundNumber: 3,
        points: 8,
      },
      {
        roundName: "Final",
        roundNumber: 4,
        points: 16,
      },
    ],
    champion: 32,
  },
  groupMatrix: [
    {
      key: "testMatrix",
      name: "Test Group Matrix",
      description: "a description goes here",
      positionInGroup: 3,
      teamsToIncludeInBracket: 4,
      matrix: {
        13: {
          ABCD: { groupName: "A", position: 3 },
          ABCE: { groupName: "A", position: 3 },
          ABCF: { groupName: "A", position: 3 },
          ABDE: { groupName: "D", position: 3 },
          ABDF: { groupName: "D", position: 3 },
          ABEF: { groupName: "E", position: 3 },
          ACDE: { groupName: "E", position: 3 },
          ACDF: { groupName: "F", position: 3 },
          ACEF: { groupName: "E", position: 3 },
          ADEF: { groupName: "E", position: 3 },
          BCDE: { groupName: "E", position: 3 },
          BCDF: { groupName: "F", position: 3 },
          BCEF: { groupName: "F", position: 3 },
          BDEF: { groupName: "F", position: 3 },
          CDEF: { groupName: "F", position: 3 },
        },
        15: {
          ABCD: { groupName: "C", position: 3 },
          ABCE: { groupName: "C", position: 3 },
          ABCF: { groupName: "C", position: 3 },
          ABDE: { groupName: "B", position: 3 },
          ABDF: { groupName: "B", position: 3 },
          ABEF: { groupName: "A", position: 3 },
          ACDE: { groupName: "A", position: 3 },
          ACDF: { groupName: "A", position: 3 },
          ACEF: { groupName: "A", position: 3 },
          ADEF: { groupName: "A", position: 3 },
          BCDE: { groupName: "C", position: 3 },
          BCDF: { groupName: "B", position: 3 },
          BCEF: { groupName: "B", position: 3 },
          BDEF: { groupName: "B", position: 3 },
          CDEF: { groupName: "C", position: 3 },
        },

        17: {
          ABCD: { groupName: "B", position: 3 },
          ABCE: { groupName: "B", position: 3 },
          ABCF: { groupName: "B", position: 3 },
          ABDE: { groupName: "A", position: 3 },
          ABDF: { groupName: "A", position: 3 },
          ABEF: { groupName: "B", position: 3 },
          ACDE: { groupName: "C", position: 3 },
          ACDF: { groupName: "C", position: 3 },
          ACEF: { groupName: "C", position: 3 },
          ADEF: { groupName: "D", position: 3 },
          BCDE: { groupName: "B", position: 3 },
          BCDF: { groupName: "C", position: 3 },
          BCEF: { groupName: "C", position: 3 },
          BDEF: { groupName: "D", position: 3 },
          CDEF: { groupName: "D", position: 3 },
        },
        19: {
          ABCD: { groupName: "D", position: 3 },
          ABCE: { groupName: "E", position: 3 },
          ABCF: { groupName: "F", position: 3 },
          ABDE: { groupName: "E", position: 3 },
          ABDF: { groupName: "F", position: 3 },
          ABEF: { groupName: "F", position: 3 },
          ACDE: { groupName: "D", position: 3 },
          ACDF: { groupName: "D", position: 3 },
          ACEF: { groupName: "F", position: 3 },
          ADEF: { groupName: "F", position: 3 },
          BCDE: { groupName: "D", position: 3 },
          BCDF: { groupName: "D", position: 3 },
          BCEF: { groupName: "E", position: 3 },
          BDEF: { groupName: "E", position: 3 },
          CDEF: { groupName: "E", position: 3 },
        },
      },
    },
  ],
};

const unevenMatches = [
  {
    matchAccepted: false,
    homeTeamName: "Team A",
    awayTeamName: "Team B",
    matchNumber: 1,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "A",
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Team C",
    awayTeamName: "Team D",
    matchNumber: 2,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "A",
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Team E",
    awayTeamName: "Team F",
    matchNumber: 3,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "B",
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Team G",
    awayTeamName: "Team H",
    matchNumber: 4,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "B",
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Team I",
    awayTeamName: "Team J",
    matchNumber: 5,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "C",
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Team K",
    awayTeamName: "Team L",
    matchNumber: 6,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "C",
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Team M",
    awayTeamName: "Team N",
    matchNumber: 7,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "D",
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Team O",
    awayTeamName: "Team P",
    matchNumber: 8,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "D",
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Team Q",
    awayTeamName: "Team R",
    matchNumber: 9,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "E",
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Team S",
    awayTeamName: "Team V",
    matchNumber: 10,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "E",
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Team W",
    awayTeamName: "Team X",
    matchNumber: 11,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "F",
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Team Y",
    awayTeamName: "Team Z",
    matchNumber: 12,
    round: 1,
    sport: "Soccer",
    type: "Group",
    groupName: "F",
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Group B Winner",
    awayTeamName: "Group A/D/E/F Third Place",
    matchNumber: 13,
    round: 1,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        groupName: "B",
        position: 1,
      },
      away: {
        groupName: "groupMatrix.testMatrix",
      },
    },
    metadata: {
      matchNumber: 39,
    },
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Group A Winner",
    awayTeamName: "Group C Runner Up",
    matchNumber: 14,
    round: 1,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        groupName: "A",
        position: 1,
      },
      away: {
        groupName: "C",
        position: 2,
      },
    },
    metadata: {
      matchNumber: 37,
    },
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Group F Winner",
    awayTeamName: "Group A/B/C Third Place",
    matchNumber: 15,
    round: 1,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        groupName: "F",
        position: 1,
      },
      away: {
        groupName: "groupMatrix.testMatrix",
      },
    },
    metadata: {
      matchNumber: 41,
    },
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Group D Runner Up",
    awayTeamName: "Group E Runner Up",
    matchNumber: 16,
    round: 1,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        groupName: "D",
        position: 2,
      },
      away: {
        groupName: "E",
        position: 2,
      },
    },
    metadata: {
      matchNumber: 42,
    },
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Group E Winner",
    awayTeamName: "Group A/B/C/D Third Place",
    matchNumber: 17,
    round: 1,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        groupName: "E",
        position: 1,
      },
      away: {
        groupName: "groupMatrix.testMatrix",
      },
    },
    metadata: {
      matchNumber: 43,
    },
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Group D Winner",
    awayTeamName: "Group F Runner Up",
    matchNumber: 18,
    round: 1,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        groupName: "D",
        position: 1,
      },
      away: {
        groupName: "F",
        position: 2,
      },
    },
    metadata: {
      matchNumber: 44,
    },
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Group C Winner",
    awayTeamName: "Group D/E/F Third Place",
    matchNumber: 19,
    round: 1,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        groupName: "C",
        position: 1,
      },
      away: {
        groupName: "groupMatrix.testMatrix",
      },
    },
    metadata: {
      matchNumber: 40,
    },
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Group A Runner Up",
    awayTeamName: "Group B Runner Up",
    matchNumber: 20,
    round: 1,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        groupName: "A",
        position: 2,
      },
      away: {
        groupName: "B",
        position: 2,
      },
    },
    metadata: {
      matchNumber: 38,
    },
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Winner 39",
    awayTeamName: "Winner 37",
    matchNumber: 21,
    round: 2,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        matchNumber: 39,
      },
      away: {
        matchNumber: 37,
      },
    },
    metadata: {
      matchNumber: 45,
    },
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Winner 41",
    awayTeamName: "Winner 42",
    matchNumber: 22,
    round: 2,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        matchNumber: 41,
      },
      away: {
        matchNumber: 42,
      },
    },
    metadata: {
      matchNumber: 46,
    },
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Winner 43",
    awayTeamName: "Winner 44",
    matchNumber: 23,
    round: 2,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        matchNumber: 43,
      },
      away: {
        matchNumber: 44,
      },
    },
    metadata: {
      matchNumber: 47,
    },
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Winner 40",
    awayTeamName: "Winner 38",
    matchNumber: 24,
    round: 2,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        matchNumber: 40,
      },
      away: {
        matchNumber: 38,
      },
    },
    metadata: {
      matchNumber: 48,
    },
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Winner 45",
    awayTeamName: "Winner 46",
    matchNumber: 25,
    round: 3,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        matchNumber: 45,
      },
      away: {
        matchNumber: 46,
      },
    },
    metadata: {
      matchNumber: 49,
    },
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Winner 47",
    awayTeamName: "Winner 48",
    matchNumber: 26,
    round: 3,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        matchNumber: 47,
      },
      away: {
        matchNumber: 48,
      },
    },
    metadata: {
      matchNumber: 50,
    },
    bracketCode: "testUnevenBracket1",
  },
  {
    matchAccepted: false,
    homeTeamName: "Winner 49",
    awayTeamName: "Winner 50",
    matchNumber: 27,
    round: 4,
    sport: "Soccer",
    type: "Playoff",
    getTeamsFrom: {
      home: {
        matchNumber: 49,
      },
      away: {
        matchNumber: 50,
      },
    },
    metadata: {
      matchNumber: 51,
    },
    bracketCode: "testUnevenBracket1",
  },
];

const prediction = {
  name: "Test Bracket",
  competitionID: "testBracket1",
  groupPredictions: [
    { groupName: "Group A", teamOrder: ["Team C", "Team A", "Team B"] },
    { groupName: "Group B", teamOrder: ["Team F", "Team D", "Team E"] },
  ],
  playoffPredictions: [
    { matchNumber: 7, homeTeam: "Team C", awayTeam: "Team D", round: 1 },
    { matchNumber: 8, homeTeam: "Team F", awayTeam: "Team A", round: 1 },
    { matchNumber: 9, homeTeam: "Team D", awayTeam: "Team F", round: 2 },
  ],
  misc: { winner: "Team D" },
};

const leaderboard = {
  predictions: [prediction],
  count: 0,
};

const user = {
  _id: "abcd",
  name: "Test User",
  email: "test@test.com",
};

export {
  competition,
  matches,
  unevenMatchesCompetition,
  unevenMatches,
  prediction,
  leaderboard,
  user,
};
